name: RECOVERY

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'Recovery Image URL (.img)'
        required: true
        default: 'https://your.site/recovery.img'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install -y git wget lz4 tar openssl python3

      - name: Download Recovery Image
        run: |
          echo "Downloading: ${{ github.event.inputs.RECOVERY_URL }}"
          curl -L "${{ github.event.inputs.RECOVERY_URL }}" -o recovery.img
          file recovery.img
          ls -lh recovery.img

      - name: Patch Process-1
        run: |
          chmod +x script1.sh magiskboot
          ./script1.sh || true

      - name: Patch Process-2
        run: |
          chmod +x script2.sh
          ./script2.sh || true

          python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
          python3 avbtool add_hash_footer \
            --partition_name recovery \
            --partition_size $(wc -c < patched-recovery.img) \
            --image patched-recovery.img \
            --key phh.pem \
            --algorithm SHA256_RSA4096

          mkdir -p output
          cp patched-recovery.img output/recovery.img
          cd output

          # Save as recovery.tar.md5
          tar -cf recovery.tar recovery.img
          md5sum -t recovery.tar >> recovery.tar
          mv recovery.tar recovery.tar.md5

      - name: Upload Recovery
        uses: actions/upload-artifact@v4
        with:
          name: Patched-Recovery
          path: output/recovery.tar.md5
